const byId=id=>document.getElementById(id);
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const uniq=a=>[...new Set(a)];
const STEP_COUNT = 6;
const STORAGE_KEY = 'yuzu_bronze_blue_v1';
let store = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{"progress":{},"settings":{"bgm":true,"se":true},"lessonTrack":{}}');
if(!store.progress) store.progress = {};
if(!store.settings) store.settings = {bgm:true,se:true};
if(!store.lessonTrack) store.lessonTrack = {};
if(!Array.isArray(store.trackOrder)||store.trackOrder.length!==10) store.trackOrder=shuffle([...Array(10).keys()]);
function saveStore(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); }
const state = {lesson:null, stage:1, idx:0, wordsQueue:[], listenQueue:[], reviewQueue:[], qaQueue:[], grammarQueue:[], sentenceQueue:[], currentChoices:[], picked:[], showJP:false, reviewSet:new Set(), currentTrack:0};
function restaurantInfo(){ const cleared = Object.values(store.progress).filter(p=>p.cleared).length; if(cleared>=10) return ['🏰','Bronze Restaurant']; if(cleared>=8) return ['🏬','Big Restaurant']; if(cleared>=6) return ['🍽️','Cafe Restaurant']; if(cleared>=4) return ['🍔','Burger Shop']; if(cleared>=2) return ['⛱️','Food Stand']; return ['🛒','やたいスタンド']; }
function updateHomeHeader(){ const cleared = Object.values(store.progress).filter(p=>p.cleared).length; byId('clearCount').textContent = cleared; byId('badgeCount').textContent = cleared; const [emo,name]=restaurantInfo(); byId('restEmoji').textContent=emo; byId('restName').textContent=name; }
function lessonProgress(n){ const p=store.progress[n]||{bestStage:0,clears:0,cleared:false}; return p; }
function renderCards(){ const cards = LESSONS.map((l,idx)=>{ const p=lessonProgress(l.n); const percent=Math.round((Math.min(p.bestStage||0,STEP_COUNT)/STEP_COUNT)*100); const colors=[['#8ec5ff','#7de2ff'],['#ffd6f0','#ffc6e5'],['#d8d1ff','#bad8ff'],['#b9f1df','#92d8ff'],['#ffe7b3','#ffd9a6'],['#ffd2cd','#ffc1bd'],['#d8e5ff','#c5d7ff'],['#d4f3ff','#c4eeff'],['#dcd7ff','#cdd3ff'],['#d7f1ff','#c7e7ff']][idx%10]; return `<button class='lessonCard' onclick='startLesson(${l.n})'>
  <div class='top'><div class='roundIcon'>${l.emoji}</div><div style='text-align:right'><div class='count'>${p.cleared?'CLEAR':'STEP'} ${p.bestStage||0}/${STEP_COUNT}</div><div class='smallTag'>Lesson ${l.n}</div></div></div>
  <h3>${l.title}</h3>
  <p>${l.words.map(w=>w[0]).join(' ・ ')}</p>
  <div class='progress'><i style='width:${percent}%;background:linear-gradient(90deg,${colors[0]},${colors[1]})'></i></div>
  <div class='lessonMeta'><span>${p.clears||0}回クリア</span><span>${percent}%</span></div>
</button>`; }).join(''); byId('cards').innerHTML = cards; renderBadges(); updateHomeHeader(); }
function renderBadges(){ const list=[]; LESSONS.forEach((l,i)=>{ const p=lessonProgress(l.n); if(p.cleared) list.push(`<div class='badge'>${BADGE_LABELS[i]}</div>`); }); byId('badgeList').innerHTML = list.length?list.join(''):'<div class="badge">まだバッジはありません</div>'; }
function startLesson(n){ playTap(); const lesson=LESSONS.find(x=>x.n===n); state.lesson=lesson; state.stage=1; state.idx=0; state.picked=[]; state.showJP=false; state.reviewSet = new Set(); state.wordsQueue = shuffle([...Array(lesson.words.length).keys()]); state.listenQueue = shuffle([...Array(lesson.words.length).keys()]); state.reviewQueue = []; state.qaQueue = shuffle([...Array(lesson.qa.length).keys()]); state.grammarQueue = shuffle([...Array(lesson.grammar.length).keys()]); state.sentenceQueue = shuffle([...Array(lesson.sentences.length).keys()]); state.currentTrack = store.trackOrder[(lesson.n-1)%BGM_TRACKS.length]; store.lessonTrack[lesson.n]=state.currentTrack; saveStore(); startBgmTrack(state.currentTrack); byId('playNav').textContent = `Lesson ${lesson.n} ・ ${lesson.title} ・ BGM: ${BGM_TRACKS[state.currentTrack].name}`; byId('playTitle').textContent = `Lesson ${lesson.n} · ${lesson.title}`; byId('home').classList.add('hidden'); byId('play').classList.remove('hidden'); render(); }
function goHome(){ playTap(); byId('play').classList.add('hidden'); byId('home').classList.remove('hidden'); renderCards(); startBgmTrack(state.currentTrack||0); }
function setProgress(stageNum){ const p = lessonProgress(state.lesson.n); p.bestStage = Math.max(p.bestStage||0, stageNum); store.progress[state.lesson.n]=p; saveStore(); }
function currentTotal(){ if(state.stage===1) return state.wordsQueue.length; if(state.stage===2) return state.listenQueue.length; if(state.stage===3) return Math.max(state.reviewQueue.length,1); if(state.stage===4) return Math.max(state.qaQueue.length,1); if(state.stage===5) return state.grammarQueue.length; if(state.stage===6) return state.sentenceQueue.length; return 1; }
function updatePlayHeader(){ ['chip1','chip2','chip3','chip4','chip5','chip6'].forEach(id=>byId(id).className='stageChip'); for(let i=1;i<=6;i++){ const chip=byId('chip'+i); if(state.stage===i) chip.classList.add('on'); else if(state.stage>i) chip.classList.add('done'); } const total=currentTotal(); byId('scorePill').textContent = `${Math.min(state.idx,total)} / ${total}`; byId('barFill').style.width = `${Math.min(100,(Math.min(state.idx,total)/Math.max(1,total))*100)}%`; }
function chooseEngOptions(correct){ const pool=uniq(LESSONS.flatMap(l=>l.words.map(w=>w[0]))).filter(x=>x!==correct); return shuffle([correct,...shuffle(pool).slice(0,3)]); }
function chooseJapOptions(correct){ const pool=uniq(LESSONS.flatMap(l=>l.words.map(w=>w[1]))).filter(x=>x!==correct); return shuffle([correct,...shuffle(pool).slice(0,3)]); }
function render(){ updatePlayHeader(); if(state.stage===1) return renderWordStep(); if(state.stage===2) return renderListenStep(); if(state.stage===3) return renderReviewStep(); if(state.stage===4) return renderQaStep(); if(state.stage===5) return renderGrammarStep(); if(state.stage===6) return renderSentenceStep(); return renderFinish(); }
function renderWordStep(){ setProgress(1); if(state.idx>=state.wordsQueue.length){ state.reviewQueue = shuffle([...state.reviewSet]); state.stage=2; state.idx=0; return render(); } const wi = state.wordsQueue[state.idx]; const w=state.lesson.words[wi]; state.currentChoices = chooseEngOptions(w[0]); byId('panelBody').innerHTML = `<div class='sub'>① 単語4択 ${state.idx+1} / ${state.wordsQueue.length}</div><div class='center'><div class='bigEmoji'>${w[2]}</div><button class='speakerBtn' onclick='playTap();speak(${JSON.stringify(w[0])})'><img src='speaker.svg' alt='speaker'><span>発音を聞く</span></button></div><div class='choiceGrid'>${state.currentChoices.map((c,i)=>`<button class='choice' onclick='answerWord(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='fb'></div>`; }
function answerWord(i){ const wi=state.wordsQueue[state.idx]; const correct=state.lesson.words[wi][0]; const ans=state.currentChoices[i]; [...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true); if(ans===correct){ document.querySelectorAll('.choice')[i].classList.add('good'); byId('fb').textContent='正解！'; playGood(); } else { document.querySelectorAll('.choice')[i].classList.add('bad'); [...document.querySelectorAll('.choice')].find(b=>b.textContent===correct)?.classList.add('good'); byId('fb').textContent=`正解は ${correct}`; state.reviewSet.add(wi); playBad(); } state.idx++; setTimeout(render,700); }
function renderListenStep(){ setProgress(2); if(state.idx>=state.listenQueue.length){ state.reviewQueue = shuffle([...state.reviewSet]); state.stage=3; state.idx=0; return render(); } const wi = state.listenQueue[state.idx]; const w=state.lesson.words[wi]; state.currentChoices = chooseJapOptions(w[1]); byId('panelBody').innerHTML = `<div class='sub'>② リスニング（日本語4択） ${state.idx+1} / ${state.listenQueue.length}</div><div class='center'><button class='speakerBtn' onclick='playTap();speak(${JSON.stringify(w[0])})'><img src='speaker.svg' alt='speaker'><span>英語を聞く</span></button><p class='note' style='margin-top:10px'>聞こえた英単語に合う日本語を選ぼう。</p></div><div class='choiceGrid'>${state.currentChoices.map((c,i)=>`<button class='choice jp' onclick='answerListen(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='fb'></div>`; setTimeout(()=>speak(w[0]), 350); }
function answerListen(i){ const wi=state.listenQueue[state.idx]; const correct=state.lesson.words[wi][1]; const ans=state.currentChoices[i]; [...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true); if(ans===correct){ document.querySelectorAll('.choice')[i].classList.add('good'); byId('fb').textContent='正解！'; playGood(); } else { document.querySelectorAll('.choice')[i].classList.add('bad'); [...document.querySelectorAll('.choice')].find(b=>b.textContent===correct)?.classList.add('good'); byId('fb').textContent=`正解は ${correct}`; state.reviewSet.add(wi); playBad(); } state.idx++; setTimeout(render,750); }
function renderReviewStep(){ setProgress(3); if(!state.reviewQueue.length){ state.stage=4; state.idx=0; return render(); } if(state.idx>=state.reviewQueue.length){ state.stage=4; state.idx=0; return render(); } const wi = state.reviewQueue[state.idx]; const w=state.lesson.words[wi]; state.currentChoices = chooseEngOptions(w[0]); byId('panelBody').innerHTML = `<div class='sub'>③ 間違い復習 ${state.idx+1} / ${state.reviewQueue.length}</div><div class='center'><div class='bigEmoji'>${w[2]}</div><button class='speakerBtn' onclick='playTap();speak(${JSON.stringify(w[0])})'><img src='speaker.svg' alt='speaker'><span>発音を聞く</span></button><p class='note' style='margin-top:10px'>まちがえた単語をもう一度。</p></div><div class='choiceGrid'>${state.currentChoices.map((c,i)=>`<button class='choice' onclick='answerReview(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='fb'></div>`; }
function answerReview(i){ const wi=state.reviewQueue[state.idx]; const correct=state.lesson.words[wi][0]; const ans=state.currentChoices[i]; [...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true); if(ans===correct){ document.querySelectorAll('.choice')[i].classList.add('good'); byId('fb').textContent='よくできた！'; playGood(); } else { document.querySelectorAll('.choice')[i].classList.add('bad'); [...document.querySelectorAll('.choice')].find(b=>b.textContent===correct)?.classList.add('good'); byId('fb').textContent=`正解は ${correct}`; playBad(); } state.idx++; setTimeout(render,700); }
function renderQaStep(){ setProgress(4); if(!state.qaQueue.length || state.idx>=state.qaQueue.length){ state.stage=5; state.idx=0; return render(); } const q = state.lesson.qa[state.qaQueue[state.idx]]; state.currentChoices = shuffle([...q.choices]); byId('panelBody').innerHTML = `<div class='sub'>④ 質問に答える ${state.idx+1} / ${state.qaQueue.length}</div><div class='qText'>${q.q}</div>${q.hint?`<div class='hint'>${q.hint}</div>`:''}<div class='choiceGrid'>${state.currentChoices.map((c,i)=>`<button class='choice${/[ぁ-んァ-ヶ一-龠]/.test(c)?' jp':''}' onclick='answerQa(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='fb'></div>`; }
function answerQa(i){ const q = state.lesson.qa[state.qaQueue[state.idx]]; const ans=state.currentChoices[i]; [...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true); if(ans===q.a){ document.querySelectorAll('.choice')[i].classList.add('good'); byId('fb').textContent='正解！'; playGood(); } else { document.querySelectorAll('.choice')[i].classList.add('bad'); [...document.querySelectorAll('.choice')].find(b=>b.textContent===q.a)?.classList.add('good'); byId('fb').textContent=`正解は ${q.a}`; playBad(); } state.idx++; setTimeout(render,700); }
function renderGrammarStep(){ setProgress(5); if(state.idx>=state.grammarQueue.length){ state.stage=6; state.idx=0; return render(); } const g = state.lesson.grammar[state.grammarQueue[state.idx]]; state.currentChoices = shuffle([...g[1]]); byId('panelBody').innerHTML = `<div class='sub'>⑤ 文法穴埋め ${state.idx+1} / ${state.grammarQueue.length}</div><div class='qText'>${g[0]}</div><p class='note center'>${g[3]}</p><div class='choiceGrid'>${state.currentChoices.map((c,i)=>`<button class='choice' onclick='answerGrammar(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='fb'></div>`; }
function answerGrammar(i){ const g = state.lesson.grammar[state.grammarQueue[state.idx]]; const ans=state.currentChoices[i]; [...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true); if(ans===g[2]){ document.querySelectorAll('.choice')[i].classList.add('good'); byId('fb').textContent='文法ばっちり！'; playGood(); } else { document.querySelectorAll('.choice')[i].classList.add('bad'); [...document.querySelectorAll('.choice')].find(b=>b.textContent===g[2])?.classList.add('good'); byId('fb').textContent=`正解は ${g[2]}`; playBad(); } state.idx++; setTimeout(render,700); }
function renderSentenceStep(){ setProgress(6); if(state.idx>=state.sentenceQueue.length){ state.stage=7; return render(); } const item = state.lesson.sentences[state.sentenceQueue[state.idx]]; const tokens = shuffle(item[0].replace(/[?.]/g,'').split(/\s+/)); state.currentChoices=tokens; state.picked=[]; byId('panelBody').innerHTML = `<div class='sub'>⑥ 並び替え ${state.idx+1} / ${state.sentenceQueue.length}</div><div style='display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:8px'><div class='note' style='margin:0;font-weight:900'>正しい順番に並べよう</div><button class='jpToggle' onclick='toggleJP(event)'>日本語 ${state.showJP?'ON':'OFF'}</button></div><div class='jpBox' id='jpBox' style='display:${state.showJP?'block':'none'}'>${item[1]}</div><div class='answerBox' id='answerBox'></div><div class='tokens'>${tokens.map((t,i)=>`<button class='token' data-i='${i}' onclick='pickToken(${i})'>${t}</button>`).join('')}</div><div class='actionRow'><button class='ghost' onclick='undoToken()'>1つ戻す</button><button class='main' onclick='checkSentence()'>答える</button></div><div class='feedback' id='fb'></div>`; }
function toggleJP(event){ playTap(); state.showJP=!state.showJP; const box=byId('jpBox'); if(box) box.style.display=state.showJP?'block':'none'; const btn=event.currentTarget; if(btn) btn.textContent=`日本語 ${state.showJP?'ON':'OFF'}`; }
function pickToken(i){ playTap(); const btn=document.querySelector(`.token[data-i="${i}"]`); if(!btn || btn.classList.contains('used')) return; btn.classList.add('used'); state.picked.push({i,word:state.currentChoices[i]}); byId('answerBox').textContent = state.picked.map(x=>x.word).join(' '); }
function undoToken(){ playTap(); const last=state.picked.pop(); if(last===undefined) return; const btn=document.querySelector(`.token[data-i="${last.i}"]`); if(btn) btn.classList.remove('used'); byId('answerBox').textContent = state.picked.map(x=>x.word).join(' '); }
function checkSentence(){ const item = state.lesson.sentences[state.sentenceQueue[state.idx]]; const target=item[0].replace(/[?.]/g,''); const mine=state.picked.map(x=>x.word).join(' '); if(mine===target){ byId('fb').textContent='正解！'; playGood(); state.idx++; setTimeout(render,700); } else { byId('fb').textContent=`もう一度！ 正解：${item[0]}`; playBad(); } }
function burstConfetti(){ const wrap=byId('confetti'); wrap.innerHTML=''; const colors=['#7dbbff','#8be0ff','#ffd6ef','#b7f2da','#d6d0ff']; for(let i=0;i<36;i++){ const s=document.createElement('span'); s.style.left=(Math.random()*100)+'vw'; s.style.background=colors[Math.floor(Math.random()*colors.length)]; s.style.transform=`translateY(0) rotate(${Math.random()*180}deg)`; s.style.animationDelay=(Math.random()*0.2)+'s'; s.style.opacity='.95'; wrap.appendChild(s); } setTimeout(()=>wrap.innerHTML='',1900); }
function renderFinish(){ setProgress(6); const p = lessonProgress(state.lesson.n); p.cleared=true; p.clears=(p.clears||0)+1; p.bestStage=6; store.progress[state.lesson.n]=p; saveStore(); updatePlayHeader(); burstConfetti(); playClear(); byId('panelBody').innerHTML = `<div class='finish'><div class='heroBadge'>🏅 ${BADGE_LABELS[state.lesson.n-1]}</div><h3>CLEAR!</h3><p class='note'>${state.lesson.title} をクリアしました。<br>また練習すると、お店もどんどん成長します。</p><div class='center' style='margin:10px auto 16px;max-width:130px'><img src='mascot.svg' alt='mascot'></div><div class='actionRow'><button class='ghost' onclick='startLesson(${state.lesson.n})'>もう一度</button><button class='main' onclick='goHome()'>Lesson一覧へ</button></div></div>`; renderCards(); }
renderCards(); updateToggles(); state.currentTrack = Object.values(store.lessonTrack)[0] || 0;

byId('bgmToggle').onclick = toggleBgm;
byId('seToggle').onclick = toggleSe;
