/* Isolated Grade 5 application. Legacy scripts are not used for Grade 5 answers. */
(function(){
'use strict';
const C=window.YuzuG5Core,B=window.YuzuG5Bank;
if(!C||!B)return;
const bank={...B.questions},legacyLessons=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hash=s=>{let n=2166136261;for(const ch of s){n^=ch.charCodeAt(0);n=Math.imul(n,16777619);}return(n>>>0).toString(36);};
// Keep the old phrase course available, with stable IDs and exact phrase order.
// Never prepend I or fabricate verb forms from an important-word field.
if(typeof G5_LESSONS!=='undefined')for(const l of G5_LESSONS){
 const lid='legacy-'+l.n,ids=[];
 const phrases=l.phrases.filter(p=>p[0]&&p[1]).map(p=>[p[0],p[1]]);
 for(const p of phrases){const en=p[0],ja=en==='She is baking a cake.'?'彼女はケーキを焼いています':p[1];
  const enOther=[...new Set(phrases.map(x=>x[0]))].filter(x=>x!==en).slice(0,3),jaOther=[...new Set(phrases.map(x=>x[1]))].filter(x=>x!==ja).slice(0,3);
  for(const type of ['vocab','wordAudio','order']){const id=lid+'-'+hash(en)+'-'+type;
   bank[id]={id,lesson:lid,type,skill:type==='order'?'語順':type==='wordAudio'?'聞き取り基礎':'語彙',prompt:type==='vocab'?en:ja,options:type==='order'?undefined:[ja,...jaOther],tokens:type==='order'?en.replace(/[.!?]$/,'').split(/\s+/):undefined,answer:type==='order'?en.replace(/[.!?]$/,''):ja,explanation:en+' = '+ja,audio:type==='wordAudio'?[en]:[]};ids.push(id);}
 }
 legacyLessons.push({id:lid,n:l.n,title:l.title,tip:l.lectureNote.replace(/<[^>]*>/g,''),example:phrases[0]?.[0]||'',ids});
}
let loaded;try{loaded=C.load(localStorage);}catch(e){loaded={state:C.fresh(),error:'このブラウザーでは記録を保存できません。'};}
let s=loaded.state,active=false,root,screen='home',selectedUnit=0,current=null,choiceOrder=[],picked=[],feedback=null,locked=false,questionStart=0,feedbackTimer=null,clockTimer=null,lastTick=0,pendingResult=null;
let saveError=loaded.error||'';
const oldSelect=window.selectCourse,oldGate=window.showCourseGate;
const top={bgm:document.getElementById('bgmToggle'),se:document.getElementById('seToggle'),reset:document.getElementById('historyResetBtn')};
const topHandlers={bgm:top.bgm?.onclick,se:top.se?.onclick};
const tracks=['hoops-bounce','moon-orbit','candy-parade','treasure-steps','aqua-groove'];
const audio={bgm:null,ctx:null,token:0,timer:null,lastTrack:-1,speaking:false,
 unlock(){try{const T=window.AudioContext||window.webkitAudioContext;if(T){this.ctx||=new T();if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}}catch{}},
 se(ok=true){if(!s.settings.se)return;this.unlock();try{const c=this.ctx;if(!c||c.state!=='running')return;const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(ok?660:240,c.currentTime);o.frequency.exponentialRampToValueAtTime(ok?990:180,c.currentTime+.15);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.10,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.22);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.23);}catch{}},
 music(change=false){if(!active)return;this.bgm||=new Audio();this.bgm.loop=true;this.bgm.volume=this.speaking?.025:.12;if(!s.settings.bgm){this.bgm.pause();return;}if(this.lastTrack<0||change){const d=new Date(),daily=(d.getFullYear()*372+d.getMonth()*31+d.getDate())%tracks.length;const ix=this.lastTrack<0?daily:C.shuffle([0,1,2,3,4].filter(i=>i!==this.lastTrack))[0];this.lastTrack=ix;this.bgm.src='assets/bgm/'+tracks[ix]+'.wav';}this.bgm.play().catch(()=>{const el=root?.querySelector('[data-audio-status]');if(el)el.textContent='BGMは上のボタンから再生できます';});},
 stopSpeech(){this.token++;clearTimeout(this.timer);if('speechSynthesis'in window)window.speechSynthesis.cancel();this.speaking=false;if(this.bgm)this.bgm.volume=.12;},
 stop(){this.stopSpeech();this.bgm?.pause();},
 say(lines,rounds=1,done=()=>{}){this.stopSpeech();if(!('speechSynthesis'in window)){audioStatus('読み上げに対応していません。別のブラウザーで音声を確認してください。');return;}const token=this.token,all=[];for(let r=0;r<rounds;r++)for(let i=0;i<lines.length;i++)all.push({text:lines[i],i,r});const voices=window.speechSynthesis.getVoices().filter(v=>/^en[-_]/i.test(v.lang));let index=0;this.speaking=true;if(this.bgm)this.bgm.volume=.025;
 const next=()=>{if(token!==this.token)return;if(index>=all.length){this.speaking=false;if(this.bgm)this.bgm.volume=.12;audioStatus('再生が終わりました');done();return;}const x=all[index++],u=new SpeechSynthesisUtterance(String(x.text));u.lang='en-US';u.rate=s.session?.mode==='mock'?.9:.82;u.pitch=x.i%2?1.08:.95;if(voices.length)u.voice=voices[x.i%Math.min(2,voices.length)];audioStatus(`${x.r+1}回目 / ${rounds}回 聞いてみよう`);u.onend=()=>{this.timer=setTimeout(next,index<all.length&&all[index].r!==x.r?1200:450);};u.onerror=e=>{if(token!==this.token||e.error==='canceled'||e.error==='interrupted')return;this.stopSpeech();audioStatus('再生できませんでした。「もう一度聞く」を押してください。');};try{window.speechSynthesis.resume();window.speechSynthesis.speak(u);}catch{this.stopSpeech();audioStatus('音声を再生できません。もう一度ボタンを押してください。');}};next();}
};
function audioStatus(text){const el=root?.querySelector('[data-audio-status]');if(el)el.textContent=text;}
function persist(){try{C.save(localStorage,s);saveError='';return true;}catch(e){saveError='記録を保存できません。設定から記録を書き出してください。';const el=root?.querySelector('[data-save-status]');if(el)el.textContent=saveError;return false;}}
function tick(){if(!s.session||screen!=='play'||document.hidden)return;const now=Date.now();if(lastTick)s.session.elapsed+=Math.max(0,Math.min(5000,now-lastTick));lastTick=now;if(s.session.mode==='mock'){const elapsed=s.session.elapsed,reading=s.session.pos<25;if(reading&&elapsed>=25*60*1000){while(s.session.pos<25){const q=bank[s.session.ids[s.session.pos]];C.answer(s,q,false);}s.session.readingDone=true;persist();renderQuestion();return;}if(!reading&&elapsed>=45*60*1000){while(s.session.pos<s.session.ids.length)C.answer(s,bank[s.session.ids[s.session.pos]],false);complete();return;}const t=root.querySelector('[data-clock]');if(t)t.textContent=clock(Math.max(0,(reading?25:45)*60000-elapsed));}}
function clock(ms){return Math.floor(ms/60000)+':'+String(Math.floor(ms%60000/1000)).padStart(2,'0');}
function pause(){tick();lastTick=0;clearInterval(clockTimer);clockTimer=null;clearTimeout(feedbackTimer);audio.stop();persist();}
function runClock(){clearInterval(clockTimer);lastTick=Date.now();clockTimer=setInterval(tick,1000);}
function header(){return `<div class="g5v-status" data-save-status role="status">${esc(saveError)}</div><div class="g5v-nav"><button data-action="home">← 5級ホーム</button><span>英検5級 ・ Yuzu English</span><button data-action="settings">⚙ 記録・音の設定</button></div>`;}
function paint(html){root.innerHTML=header()+html;window.scrollTo({top:0,behavior:'instant'});}
function mount(){if(!root){root=document.createElement('section');root.id='g5V2';root.className='g5v';document.querySelector('.app').appendChild(root);root.addEventListener('click',onClick);root.addEventListener('change',onChange);}root.hidden=false;}
function setTop(){if(top.bgm){top.bgm.textContent=s.settings.bgm?'🎵 BGM ON':'🎵 BGM OFF';top.bgm.onclick=()=>{audio.unlock();s.settings.bgm=!s.settings.bgm;audio.music();persist();setTop();};}if(top.se){top.se.textContent=s.settings.se?'🔔 SE ON':'🔔 SE OFF';top.se.onclick=()=>{s.settings.se=!s.settings.se;audio.se();persist();setTop();};}if(top.reset)top.reset.hidden=true;}
window.selectCourse=function(course){if(course!=='grade5'){if(active){pause();active=false;if(root)root.hidden=true;if(top.bgm)top.bgm.onclick=topHandlers.bgm;if(top.se)top.se.onclick=topHandlers.se;if(top.reset)top.reset.hidden=false;if(typeof updateToggles==='function')updateToggles();}const result=oldSelect(course);if(typeof startBgmTrack==='function'&&typeof state!=='undefined')startBgmTrack(state.currentTrack||0);return result;}
 document.getElementById('courseGate')?.classList.add('hidden');for(const id of ['home','play','g5Home','g5Play'])document.getElementById(id)?.classList.add('hidden');try{bgmAudio.pause();}catch{}active=true;mount();setTop();audio.unlock();audio.music();renderHome();};
window.showCourseGate=function(){if(active)pause();if(typeof oldGate==='function')return oldGate();document.getElementById('courseGate')?.classList.remove('hidden');};
if(!document.getElementById('courseGate')){const gate=document.createElement('div');gate.id='courseGate';gate.className='courseGate';gate.innerHTML='<div class="courseGateIn"><h1>Yuzu English</h1><button id="g5RecoveryEntry">⭐ 英検5級を開く</button></div>';document.body.appendChild(gate);document.getElementById('g5RecoveryEntry').onclick=()=>window.selectCourse('grade5');}
const switchButton=document.querySelector('.courseSwitch');if(switchButton)switchButton.onclick=window.showCourseGate;
const courseTag=document.querySelector('.courseCard.grade5 .courseTag');if(courseTag)courseTag.textContent='合格レッスン30 + 復習 + 本番対策';
function renderHome(){screen='home';pause();audio.music();const town=C.town(s),due=C.reviewIds(s,bank,{limit:9999}).length,done=B.lessons.filter(l=>s.lessons[l.id]?.cleared).length;const next=B.lessons.find(l=>!s.lessons[l.id]?.cleared)||B.lessons[0];
 paint(`<div class="g5v-hero"><div><span class="g5v-eyebrow">YUZU ENGLISH / GRADE 5</span><h1>🏀 今日の一歩が、合格につながる。</h1><p>短いレッスンで、ことば・文法・会話・聞く力を育てよう。</p><div class="g5v-pills"><span>合格レッスン ${done}/30</span><span>復習待ち ${due}問</span><span>⭐ ${s.coins} コイン</span></div></div><div class="g5v-start"><button class="primary" data-action="start" data-id="${next.id}">▶ ${done===30?'もう一度練習':'今日のレッスン'}</button><small>${esc(next.title)} ・ 約10〜15分</small>${s.session?'<button data-action="resume">↩ 途中からつづける</button>':''}<button data-action="review" ${due?'':'disabled'}>↻ 苦手を復習する ${due?`（${Math.min(due,10)}問）`:''}</button></div></div>
 <section class="g5v-town"><div class="g5v-sectionhead"><h2>ゆづのバスケタウン</h2><b>${town.count} CLEAR</b></div><p>${town.next?`あと ${town.next-town.count} クリアで、街が成長するよ！`:'アリーナ完成！ 復習して街を飾ろう。'}</p><div class="g5v-town-grid">${[1,2,3].map((n)=>`<div class="g5v-town-card ${town.stage>=n?'unlocked':'locked'}"><h3>STEP ${n} · ${['YUZU HOOPS','HOOPS TOWN','YUZU ARENA'][n-1]}</h3><img src="assets/basket-town-stage${n}.webp" alt="${n===1?'バスケットコート':n===2?'バスケタウン':'アリーナ'}" width="800" height="600" ${n>1?'loading="lazy"':''} decoding="async"><p>${town.stage>=n?'✨ オープン！':`${[1,10,20][n-1]} CLEARでオープン`}</p></div>`).join('')}</div><div class="g5v-town-decor" aria-label="街の飾り">${s.purchases.map(id=>`<span>${shop.find(x=>x.id===id)?.icon||'⭐'} ${esc(shop.find(x=>x.id===id)?.name||'')}</span>`).join('')||'<span>コインで街に飾りを増やそう</span>'}</div><button data-action="shop">🛍 街のショップへ</button></section>
 <div class="g5v-sectionhead"><h2>合格レッスン</h2><button data-action="stats">📊 がんばりの記録</button></div><div class="g5v-units" role="group" aria-label="学習ブロック">${B.units.map((u,i)=>`<button data-action="unit" data-id="${i}" aria-pressed="${i===selectedUnit}">${i+1}. ${esc(u)}</button>`).join('')}</div><div class="g5v-lessons">${B.lessons.filter(l=>l.unit===selectedUnit).map(lessonCard).join('')}</div>
 <section class="g5v-practice"><h2>本番の形で練習しよう</h2><p>すべてオリジナル問題。音声はブラウザーの読み上げです。</p><div class="g5v-practice-grid">${[['grammar','語句・文法4択'],['conversation','会話4択'],['examOrder','本番の語句整序'],['response','音声の返事3択'],['dialog','対話を聞いて4択'],['picture','絵と音声3択']].map(([id,name])=>`<button data-action="practice" data-id="${id}">${name}</button>`).join('')}<button class="primary" data-action="mockIntro">🏆 50問の本番チャレンジ</button></div></section>
 <details class="g5v-legacy"><summary>📚 これまでのフレーズ練習・クリア記録（30 Lesson）</summary><p>以前のクリア記録はそのまま。正しいフレーズの意味・音・語順を練習できます。各回は未定着のフレーズを中心に最大12問。</p><div class="g5v-lessons">${legacyLessons.map(lessonCard).join('')}</div></details><p class="g5v-foot">英検®の公式アプリではありません。合否は公式試験で判定されます。<a href="https://www.eiken.or.jp/eiken/exam/grade_5/solutions.html" target="_blank" rel="noopener">公式の出題形式</a></p>`);
}
function lessonCard(l){const p=s.lessons[l.id]||{},old=s.legacy['lesson'+l.n],legacy=l.id.startsWith('legacy-'),cleared=p.cleared||(legacy&&old?.cleared);return `<button class="g5v-lesson ${cleared?'cleared':''} ${p.perfect?'perfect':''}" data-action="start" data-id="${l.id}"><span>${legacy?'PHRASES':'LESSON'} ${l.n} ${p.perfect?'🏆':cleared?'✓':''}</span><h3>${esc(l.title)}</h3><small>${p.clears?`初回正答率ベスト ${p.best}%`:(legacy&&old?.cleared)?`以前のCLEAR${old.perfect?'・旧PERFECT':''}`:'これから練習'}</small><div class="g5v-progress"><i style="width:${cleared?100:0}%"></i></div></button>`;}
function findLesson(id){return B.lessons.find(l=>l.id===id)||legacyLessons.find(l=>l.id===id);}
function askReplace(){if(!s.session)return true;return confirm('途中のレッスンがあります。ここまでの回答記録は残して、新しい練習を始めますか？');}
function intro(id){const l=findLesson(id);if(!l)return;if(s.session?.lesson===id){resume();return;}if(!askReplace())return;screen='intro';pause();paint(`<article class="g5v-panel g5v-intro"><span class="g5v-eyebrow">${id.startsWith('legacy-')?'フレーズ練習':'LESSON '+l.n}</span><h1>${esc(l.title)}</h1><div class="g5v-teach">${esc(l.tip)}</div><div class="g5v-example">${esc(l.example)}</div><p>間違えても大丈夫。正解まで練習して、少し後でもう一度思い出そう。</p><div class="g5v-actions"><button data-action="example" data-id="${id}">🔊 例を聞く</button><button class="primary" data-action="begin" data-id="${id}">練習スタート</button></div><p data-audio-status role="status"></p></article>`);}
function begin(id){const l=findLesson(id);if(!l)return;let ids=l.ids;if(id.startsWith('legacy-')){ids=[...ids].sort((a,b)=>(s.items[a]?.seen||0)-(s.items[b]?.seen||0));ids=ids.slice(0,12);}const due=C.reviewIds(s,bank,{limit:3,exclude:ids});s.session=C.session(id,[...due,...ids],id.startsWith('legacy-')?'legacy':'learn');s.session.reviewCount=due.length;persist();screen='play';audio.unlock();audio.music(true);runClock();renderQuestion();}
function resume(){if(!s.session)return;const invalid=s.session.ids.some(id=>!bank[id]);if(invalid){saveError='途中の問題を復元できませんでした。回答履歴は残っています。新しい練習を選んでください。';renderHome();return;}screen='play';audio.unlock();audio.music();runClock();renderQuestion();}
function practice(type){if(!askReplace())return;let pool=Object.values(bank).filter(q=>q.lesson!=='shared'&&!q.lesson.startsWith('legacy-')&&q.type===(type==='examOrder'?'order':type));if(type==='picture')pool=Object.values(bank).filter(q=>q.type==='picture');if(type==='examOrder'){pool=pool.map(examVersion);}const ids=C.shuffle(pool).slice(0,10).map(q=>q.id);s.session=C.session('practice-'+type,ids,'practice');persist();screen='play';audio.music(true);runClock();renderQuestion();}
function startReview(){if(!askReplace())return;const ids=C.reviewIds(s,bank,{limit:10});if(!ids.length){renderHome();return;}s.session=C.session('review',ids,'review');persist();screen='play';audio.music(true);runClock();renderQuestion();}
function examVersion(q){const id=q.id+'-exam';if(!bank[id])bank[id]={...q,id,type:'examOrder'};return bank[id];}
// These IDs also exist before resume/restore, not only after entering practice.
Object.values(bank).filter(q=>q.type==='order'&&!q.lesson.startsWith('legacy-')).forEach(examVersion);
function mockIntro(){screen='mockIntro';pause();paint(`<article class="g5v-panel"><h1>🏆 本番チャレンジ</h1><p>リーディング25問・25分 ＋ リスニング25問・約20分。</p><p>問題はすべてオリジナル。語順は、並べた語句の<strong>1番目と3番目</strong>を選びます。音声は2回流れます。</p><p>このモードは最初の答えで採点します。解き直しは最後にまとめて。音声は各問の再生ボタンで開始するので、放送が自動で進む本番とは操作が異なります。</p><p>途中で休憩・保存できます。各パートの制限時間が来たら未回答を不正解として次へ進みます。</p><button class="primary" data-action="mock">50問に挑戦する</button></article>`);}
function startMock(){if(!askReplace())return;const pool=type=>Object.values(bank).filter(q=>q.type===type&&!q.lesson.startsWith('legacy-'));const ids=[...C.shuffle(pool('grammar')).slice(0,15),...C.shuffle(pool('conversation')).slice(0,5),...C.shuffle(pool('examOrder')).slice(0,5),...C.shuffle(pool('response')).slice(0,10),...C.shuffle(pool('dialog')).slice(0,5),...C.shuffle(pool('picture')).slice(0,10)].map(q=>q.id);s.session=C.session('mock',ids,'mock');persist();screen='play';audio.music(true);runClock();renderQuestion();}
function renderQuestion(){clearTimeout(feedbackTimer);audio.stopSpeech();locked=false;feedback=null;const r=s.session;if(!r)return renderHome();if(r.pos>=r.ids.length)return complete();if(r.mode==='mock'&&r.pos===25&&!r.readingDone){r.readingDone=true;r.elapsed=25*60000;persist();}current=bank[r.ids[r.pos]];if(!current){saveError='この問題を読み込めません。記録を書き出して保護者に知らせてください。';return renderHome();}choiceOrder=C.shuffle(current.options||[]);picked=[];questionStart=Date.now();if(current.type==='order'||current.type==='examOrder'){choiceOrder=C.shuffle(current.tokens.map((text,index)=>({text,index})));if(current.type==='examOrder'){const a=choiceOrder.findIndex(t=>t.index===0)+1,c=choiceOrder.findIndex(t=>t.index===2)+1;currentExamAnswer=`${a} → ${c}`;const pairs=[];for(let x=1;x<=4;x++)for(let y=1;y<=4;y++)if(x!==y&&`${x} → ${y}`!==currentExamAnswer)pairs.push(`${x} → ${y}`);examChoices=C.shuffle([currentExamAnswer,...C.shuffle(pairs).slice(0,3)]);}}
 drawQuestion();}
let examChoices=[],currentExamAnswer='';
function drawQuestion(){const r=s.session,q=current;if(!r||!q)return;const lesson=findLesson(r.lesson),listening=['wordAudio','response','dialog','picture'].includes(q.type),hiddenOptions=['response','picture'].includes(q.type);let question='';
 if(q.scene)question+=sceneSvg(q.scene);
 question+=`<h2 class="g5v-prompt">${esc(q.type==='wordAudio'?'英語を聞いて意味を選ぼう':q.prompt).replace(/\n/g,'<br>')}</h2>`;
 if(listening)question+=`<div class="g5v-listen"><button class="primary" data-action="listen">🔊 ${r.mode==='mock'&&r.audioPlayed?.[r.pos]?'再生済み':'英語を聞く'}${q.type==='wordAudio'?'':'（2回）'}</button><p data-audio-status role="status">${r.mode==='mock'?'本番練習では再生は1セットです':'再生できないときは、もう一度押してね'}</p></div>`;
 if(q.type==='order'){question+=`<div class="g5v-answer" aria-live="polite">${picked.map(i=>esc(choiceOrder[i].text)).join(' ')||'<span>単語を順番にタップ</span>'}</div><div class="g5v-tokens">${choiceOrder.map((t,i)=>`<button data-action="token" data-id="${i}" ${picked.includes(i)?'disabled':''}>${esc(t.text)}</button>`).join('')}</div><div class="g5v-actions"><button data-action="undo" ${picked.length?'':'disabled'}>1つ戻す</button><button class="primary" data-action="orderAnswer" ${picked.length===choiceOrder.length?'':'disabled'}>答える</button></div>`;}
 else if(q.type==='examOrder'){question+=`<p class="g5v-exam-help">日本語に合う順に並べたとき、<b>1番目 → 3番目</b>の語句の番号は？</p><div class="g5v-order-list">${choiceOrder.map((t,i)=>`<span>${i+1}. ${esc(t.text)}</span>`).join('')}</div><div class="g5v-choices">${examChoices.map((x,i)=>`<button data-action="answer" data-id="${i}">${esc(x)}</button>`).join('')}</div>`;}
 else question+=`<div class="g5v-choices ${hiddenOptions?'audio-choices':''}">${choiceOrder.map((x,i)=>`<button data-action="answer" data-id="${i}"><span class="g5v-number">${i+1}</span>${hiddenOptions?'番':esc(x)}</button>`).join('')}</div>`;
 paint(`<article class="g5v-panel"><div class="g5v-playhead"><div><span class="g5v-eyebrow">${r.mode==='mock'?(r.pos<25?'READING':'LISTENING'):r.mode==='review'?'REVIEW':r.pos<(r.reviewCount||0)?'前のレッスンを復習':q.checkpoint?'🔥 本番ミニ問題':esc(q.skill)}</span><h1>${esc(lesson?.title||(r.mode==='mock'?'本番チャレンジ':'集中トレーニング'))}</h1></div><span>${r.pos+1} / ${r.ids.length}${r.mode==='mock'?`<b data-clock>${clock(Math.max(0,(r.pos<25?25:45)*60000-r.elapsed))}</b>`:''}</span></div><div class="g5v-progress"><i style="width:${r.pos/r.ids.length*100}%"></i></div><div class="g5v-question">${question}</div><div class="g5v-feedback" aria-live="polite"></div><div class="g5v-bottom"><button data-action="pause">⏸ 休憩して保存</button>${r.mode!=='mock'?'<button data-action="hint">💡 ヒントを見る</button>':''}</div></article>`);
}
function listen(){const r=s.session,q=current;if(!r||!q)return;if(r.mode==='mock'&&r.audioPlayed?.[r.pos]){audioStatus('この問題は2回再生済みです。答えを選んでください。');return;}let lines=[...(q.audio||[])];if(q.type==='response'||q.type==='picture')lines.push(...choiceOrder.map((x,i)=>`${i+1}. ${x}`));audio.say(lines,q.type==='wordAudio'?1:2,()=>{if(s.session===r){r.audioPlayed||={};r.audioPlayed[r.pos]=true;persist();}});}
function answer(index){if(locked||!s.session)return;const q=current,r=s.session;let chosen;if(q.type==='order')chosen=picked.map(i=>choiceOrder[i].text).join(' ');else chosen=q.type==='examOrder'?examChoices[index]:choiceOrder[index];if(chosen===undefined)return;const correct=q.type==='examOrder'?currentExamAnswer:q.answer,ok=chosen===correct;locked=true;audio.stopSpeech();const pos=r.pos;tick();if(s.session!==r||r.pos!==pos)return;C.answer(s,q,ok);persist();audio.se(ok);root.querySelectorAll('[data-action="answer"],[data-action="orderAnswer"],[data-action="token"],[data-action="undo"],[data-action="listen"],[data-action="hint"]').forEach(b=>b.disabled=true);
 if(r.mode==='mock'){feedbackTimer=setTimeout(()=>{if(s.session===r&&screen==='play')renderQuestion();},220);return;}
 const fb=root.querySelector('.g5v-feedback');fb.classList.add(ok?'good':'bad');fb.innerHTML=`<strong>${ok?'ナイス！ 正解！':'あと少し。もう一度やってみよう。'}</strong><p>${esc(q.explanation)}</p>${!ok&&['response','dialog','picture','wordAudio'].includes(q.type)?`<details><summary>英文を見て確かめる</summary><p>${esc([...(q.audio||[]),...(['response','picture'].includes(q.type)?choiceOrder:[])].join('\n')).replace(/\n/g,'<br>')}</p></details>`:''}<button class="${ok?'primary':''}" data-action="${ok?'next':'retry'}">${ok?(r.pos===r.ids.length?'結果を見る':'次へ'):'同じ問題に再挑戦'}</button>`;
 if(ok&&pos%4===3)fb.insertAdjacentHTML('afterbegin','<span class="g5v-shot" aria-hidden="true">🏀 ✨</span>');fb.scrollIntoView({block:'nearest',behavior:'smooth'});
}
function complete(){tick();clearInterval(clockTimer);lastTick=0;audio.stopSpeech();pendingResult=C.finish(s);persist();if(!pendingResult)return renderHome();renderResult(pendingResult);}
function renderResult(h){screen='result';const perfect=h.wrong.length===0;paint(`<article class="g5v-panel g5v-result"><div class="g5v-trophy">${perfect?'🏆':'🏀'}</div><h1>${perfect?'よくできた！':'最後までがんばったね！'}</h1><p>初回正解 <strong>${h.score} / ${h.total}</strong> ・ ⭐ +${h.coins||0}コイン</p><p>${h.mode==='mock'?'これはオリジナル模試の成績です。英検CSEスコアや公式の合否ではありません。':'間違えた問題は正解まで練習しました。後のレッスンでもまた思い出そう。'}</p>${statsTable(h.stats)}${h.wrong.length?`<h2>今日のまちがいノート</h2><div class="g5v-mistakes">${h.wrong.map(id=>{const q=bank[id];return q?`<div><strong>${esc(q.skill)}</strong><p>${esc(q.explanation)}</p><button data-action="speakQuestion" data-id="${esc(id)}">🔊 英語を聞く</button></div>`:'';}).join('')}</div><button data-action="retryResult">間違えた問題だけ練習</button>`:'<p>✨ 全問、最初の答えで正解！</p>'}<div class="g5v-actions"><button class="primary" data-action="home">街の成長を見に行く</button><button data-action="shoot">🏀 ごほうびシュート</button></div><div data-shoot-area></div></article>`);audio.se(true);}
function statsTable(stats){return `<table class="g5v-table"><thead><tr><th>分野</th><th>初回正解</th></tr></thead><tbody>${Object.entries(stats||{}).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.correct} / ${v.total}</td></tr>`).join('')}</tbody></table>`;}
function renderStats(){screen='stats';pause();const total={},mastered=Object.values(s.items).filter(p=>p.box>=3).length;for(const h of s.history)for(const [k,v]of Object.entries(h.stats||{})){total[k]||={correct:0,total:0};total[k].correct+=v.correct;total[k].total+=v.total;}paint(`<article class="g5v-panel"><h1>📊 がんばりの記録</h1><p>後日の復習で定着してきた問題：${mastered}問 ／ 学習した問題：${Object.keys(s.items).length}問</p><p>初回正答率は、その回で初めて答えたときの成績。ヒントを見た回答は定着判定を進めません。</p>${statsTable(total)}<h2>最近の学習</h2>${s.history.slice(0,12).map(h=>`<div class="g5v-history"><span>${esc(new Date(h.date).toLocaleDateString('ja-JP'))} · ${esc(findLesson(h.lesson)?.title||({mock:'本番チャレンジ',review:'弱点復習'}[h.mode]||'集中練習'))}</span><b>${h.score}/${h.total}</b></div>`).join('')||'<p>レッスンを終えると、ここに記録がたまります。</p>'}</article>`);}
const shop=[{id:'ball',icon:'🏀',name:'カラフルボール',cost:30},{id:'flag',icon:'🚩',name:'チームの旗',cost:50},{id:'jersey',icon:'🎽',name:'ユニフォーム',cost:70},{id:'fans',icon:'📣',name:'応援スタンド',cost:100},{id:'tree',icon:'🌳',name:'街路樹',cost:40},{id:'star',icon:'🌟',name:'アリーナの星',cost:120}];
function renderShop(){screen='shop';pause();paint(`<article class="g5v-panel"><h1>🛍 バスケタウンのショップ</h1><p>⭐ ${s.coins} コイン。買った飾りはホームの街に並ぶよ。</p><div class="g5v-shop">${shop.map(x=>`<div><span>${x.icon}</span><h2>${x.name}</h2><p>⭐ ${x.cost}</p><button data-action="buy" data-id="${x.id}" ${s.purchases.includes(x.id)||s.coins<x.cost?'disabled':''}>${s.purchases.includes(x.id)?'街にかざっています':'街にかざる'}</button></div>`).join('')}</div><p>初回クリア+20、1日最初の完走+10、1日1回のノーミス復習+10。ノーミスの初回ボーナス+5。同じ問題の連打ではコインは増えません。</p></article>`);}
function settings(){screen='settings';pause();paint(`<article class="g5v-panel"><h1>⚙ 5級の記録・音の設定</h1><p>記録はこのブラウザーに保存されます。別の端末に移すときは書き出し・読み込みを使ってください。</p><div class="g5v-actions"><button data-action="export">記録を書き出す</button><label class="g5v-file">記録を読み込む<input type="file" accept="application/json,.json" data-import></label></div><p>5級だけの記録です。ブロンズには影響しません。</p><div class="g5v-actions"><button data-action="audioTest">🔊 英語と効果音を確認</button><button data-action="restoreBackup">直前の保存に戻す</button></div><p data-audio-status role="status"></p><details><summary>保護者向け：5級の記録をリセット</summary><p>5級のクリア・復習・コインをリセットします。実行前に記録を書き出せます。</p><button class="danger" data-action="reset">5級の記録をリセット</button></details></article>`);}
function download(){const blob=new Blob([JSON.stringify({app:'Yuzu English Grade5',exported:new Date().toISOString(),state:s},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='yuzu-grade5-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function onChange(e){if(!e.target.matches('[data-import]'))return;const file=e.target.files?.[0];if(!file)return;if(file.size>5000000){alert('ファイルが大きすぎます。Yuzu Englishの記録ファイルを選んでください。');return;}file.text().then(text=>{let next;try{const data=JSON.parse(text);next=C.validate(data.state||data);if(next.session?.ids.some(id=>!bank[id]))throw Error('途中の問題がこのバージョンと合いません');}catch(error){alert('読み込めません：'+error.message);return;}if(!confirm('現在の5級の記録を、選んだファイルの記録に入れ替えますか？'))return;s=next;persist();setTop();renderHome();}).catch(()=>alert('ファイルを読み込めませんでした。'));}
function onClick(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;audio.unlock();switch(a){case'home':renderHome();break;case'unit':selectedUnit=Number(id);renderHome();break;case'start':intro(id);break;case'begin':begin(id);break;case'example':audio.say([findLesson(id).example]);break;case'resume':resume();break;case'pause':renderHome();break;case'practice':practice(id);break;case'review':startReview();break;case'mockIntro':mockIntro();break;case'mock':startMock();break;case'listen':listen();break;case'answer':answer(Number(id));break;case'orderAnswer':answer();break;case'token':if(!locked&&!picked.includes(Number(id))){picked.push(Number(id));drawQuestion();}break;case'undo':if(!locked){picked.pop();drawQuestion();}break;case'next':case'retry':renderQuestion();break;case'hint':if(s.session){s.session.hinted[s.session.pos]=true;persist();const fb=root.querySelector('.g5v-feedback');fb.innerHTML=`<p>💡 ${esc(current.explanation)}</p>`;}break;case'stats':renderStats();break;case'shop':renderShop();break;case'buy':{const x=shop.find(x=>x.id===id);if(x&&!s.purchases.includes(id)&&s.coins>=x.cost){s.coins-=x.cost;s.purchases.push(id);persist();audio.se();renderShop();}break;}case'settings':settings();break;case'export':download();break;case'audioTest':audio.se();audio.say(['Hello, Yuzu. Let us play basketball.']);break;case'retryResult':if(pendingResult?.wrong.length){s.session=C.session('review',pendingResult.wrong,'review');persist();resume();}break;case'speakQuestion':{const q=bank[id];if(q)audio.say(q.audio?.length?q.audio:[q.type==='vocab'?q.prompt:q.type==='order'||q.type==='examOrder'?q.tokens.join(' '):q.answer]);break;}case'shoot':{const area=root.querySelector('[data-shoot-area]');if(area){area.innerHTML='<div class="g5v-shoot"><span class="g5v-flying-ball">🏀</span><span>🥅</span><b>ナイスシュート！ 今日も一歩前進！</b></div>';audio.se();}break;}case'restoreBackup':try{const raw=localStorage.getItem(C.KEY+'_backup');if(!raw){alert('直前の保存がありません。');break;}const next=C.validate(JSON.parse(raw));if(confirm('5級の記録を直前の保存に戻しますか？')){s=next;persist();renderHome();}}catch{alert('バックアップを読み込めませんでした。');}break;case'reset':if(confirm('5級だけの記録をリセットしますか？ 必要なら先に「記録を書き出す」を使ってください。')){const settings=s.settings;s=C.fresh();s.settings=settings;persist();renderHome();}break;}}
function sceneSvg(type){const common='<svg viewBox="0 0 420 200" role="img" aria-label="問題のイラスト" class="g5v-scene"><rect x="2" y="2" width="416" height="196" rx="26" fill="#eff8ff"/><path d="M25 174H395" stroke="#bad8e9" stroke-width="4"/>';
const head=(x,y)=>`<circle cx="${x}" cy="${y}" r="18" fill="#f8c9a0" stroke="#845b48" stroke-width="2"/><path d="M${x-17} ${y-5}q17 -28 34 0" fill="#654335"/><circle cx="${x-6}" cy="${y}" r="2"/><circle cx="${x+6}" cy="${y}" r="2"/><path d="M${x-5} ${y+8}q5 4 10 0" fill="none" stroke="#845b48" stroke-width="2"/>`;
const desk='<path d="M130 108H300M145 108V173M284 108V173" stroke="#8a6046" stroke-width="9" fill="none"/>';
const bag=(x,y)=>`<rect x="${x}" y="${y}" width="46" height="40" rx="7" fill="#f3a642" stroke="#a86c21" stroke-width="3"/><path d="M${x+12} ${y}v-9h22v9" stroke="#a86c21" stroke-width="4" fill="none"/>`;
let art='';if(type==='conversation'){art=head(115,86)+head(305,86)+'<path d="M88 166v-48q27 -24 54 0v48" fill="#61a9ee"/><path d="M278 166v-48q27 -24 54 0v48" fill="#ee987d"/><path d="M165 38h95v42h-70l-14 15v-15h-11z" fill="white" stroke="#93badb" stroke-width="3"/><circle cx="190" cy="59" r="4" fill="#93badb"/><circle cx="214" cy="59" r="4" fill="#93badb"/><circle cx="238" cy="59" r="4" fill="#93badb"/>';}
else if(type==='clock'){art='<circle cx="210" cy="98" r="73" fill="white" stroke="#5c94ca" stroke-width="7"/><text x="210" y="48" text-anchor="middle" font-size="21" fill="#436384">12</text><text x="266" y="106" text-anchor="middle" font-size="21" fill="#436384">3</text><text x="210" y="161" text-anchor="middle" font-size="21" fill="#436384">6</text><text x="152" y="106" text-anchor="middle" font-size="21" fill="#436384">9</text><path d="M210 98V58M210 98L189 134" stroke="#345572" stroke-width="6" stroke-linecap="round"/><circle cx="210" cy="98" r="6" fill="#f49643"/>';}
else if(type==='apples'){art=[115,210,305].map(x=>`<path d="M${x} 73c-40 -23-61 28-34 62q34 33 68 0c27-34 6-85-34-62" fill="#ee736b" stroke="#b64643" stroke-width="3"/><path d="M${x} 75v-23" stroke="#79593d" stroke-width="5"/><ellipse cx="${x+14}" cy="56" rx="17" ry="8" transform="rotate(-25 ${x+14} 56)" fill="#70b86d"/>`).join('');}
else if(type==='under'||type==='ontable'){art=desk+(type==='under'?bag(185,130):'<path d="M182 94h62v11h-62z" fill="#6ca9e8" stroke="#3e729c" stroke-width="3"/><path d="M185 100h55" stroke="white" stroke-width="3"/>');}
else if(type==='door'){art='<rect x="110" y="25" width="115" height="148" rx="3" fill="#dab798" stroke="#8a6046" stroke-width="5"/><circle cx="207" cy="100" r="5" fill="#c39427"/>'+bag(265,132);}
else if(type==='cats'){art=[140,285].map(x=>`<ellipse cx="${x}" cy="138" rx="34" ry="36" fill="#edba7f"/><path d="M${x+28} 146q40 20 35-20" fill="none" stroke="#edba7f" stroke-width="12"/><path d="M${x-27} 88v-26l20 15h14l20-15v26" fill="#edba7f"/><ellipse cx="${x}" cy="95" rx="29" ry="26" fill="#edba7f"/><circle cx="${x-10}" cy="93" r="3"/><circle cx="${x+10}" cy="93" r="3"/><path d="M${x-3} 104h6l-3 4z" fill="#9a6062"/>`).join('');}
else if(type==='reading'){art=head(210,58)+'<path d="M177 152v-59q33-25 66 0v59" fill="#62a9ea"/><path d="M174 148v25m72-25v25" stroke="#455e82" stroke-width="11"/><path d="M210 107l-45-13v40l45 15 45-15V94z" fill="#f3a646" stroke="#9c723c" stroke-width="3"/><path d="M210 107v42" stroke="#fff0ca" stroke-width="3"/>';}
else if(type==='swimming'){art='<rect x="35" y="122" width="350" height="50" rx="10" fill="#7bcee8"/>'+head(250,100)+'<path d="M128 138l72-14 50 10m-65-10-30-29-39 12" fill="none" stroke="#679fd6" stroke-width="14" stroke-linecap="round"/><path d="M40 147q20-15 40 0t40 0t40 0t40 0t40 0t40 0t40 0t40 0" fill="none" stroke="white" stroke-width="3"/>';}
else if(type==='rain'){art=head(205,90)+'<path d="M188 172V115h34v57" fill="#f4bd48"/><path d="M125 64q75-100 150 0z" fill="#a88cdd"/><path d="M202 65v62q0 18 15 9" fill="none" stroke="#556c8a" stroke-width="4"/>'+[50,82,310,350,110,290,365].map((x,i)=>`<path d="M${x} ${25+(i%3)*40}l-7 20" stroke="#73add9" stroke-width="4"/>`).join('');}
else{art=head(190,57)+'<path d="M176 87l27 40m-11-26-38 16m42-15 38-25m-31 50-37 43m37-43 39 26" fill="none" stroke="#5d92cf" stroke-width="13" stroke-linecap="round"/>';if(type==='soccer')art+='<circle cx="296" cy="155" r="20" fill="white" stroke="#4b5c73" stroke-width="3"/><path d="M291 143l13 3 3 13-13 6-10-10z" fill="#4b5c73"/>';if(type==='basketball')art+='<path d="M346 50V173" stroke="#7089a5" stroke-width="6"/><rect x="313" y="26" width="60" height="42" fill="white" stroke="#769bc2" stroke-width="3"/><path d="M312 65h49l-9 27h-31z" fill="none" stroke="#db7a56" stroke-width="3"/><circle cx="267" cy="54" r="17" fill="#ee9942" stroke="#9c5e31" stroke-width="2"/>';if(type==='running')art+='<path d="M97 93h42m-54 22h40m-30 23h28" stroke="#a6cde5" stroke-width="5" stroke-linecap="round"/>';}
return common+art+'</svg>';}
document.addEventListener('visibilitychange',()=>{if(!active)return;if(document.hidden){pause();}else{lastTick=0;if(screen==='play'){runClock();audioStatus('おかえり！ 音声はボタンから再生できます。');}}});window.addEventListener('pagehide',()=>{if(active)pause();});
})();
