/* Grade 5 only. Pure, versioned learning state; no Bronze dependencies. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.YuzuG5Core=api;})(typeof window==='object'?window:this,function(){
'use strict';
const VERSION=2,KEY='yuzu_g5_v2',DAY=86400000;
const shuffle=(a,rng=Math.random)=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
function fresh(){return {version:VERSION,lessons:{},items:{},coins:0,earned:{},purchases:[],history:[],session:null,legacy:{},settings:{bgm:true,se:true},dayRewards:{}};}
function validate(s){
 const obj=x=>x&&typeof x==='object'&&!Array.isArray(x);
 if(!obj(s)||s.version!==VERSION||!obj(s.lessons)||!obj(s.items)||!obj(s.earned)||!obj(s.legacy)||!obj(s.dayRewards)||!obj(s.settings)||typeof s.settings.bgm!=='boolean'||typeof s.settings.se!=='boolean'||!Number.isFinite(s.coins)||s.coins<0||!Array.isArray(s.history)||s.history.length>100||!Array.isArray(s.purchases)||!s.purchases.every(x=>typeof x==='string'))throw Error('保存データの形式が違います');
 for(const x of Object.values(s.items)){if(!obj(x)||!Number.isFinite(x.due)||!Number.isInteger(x.box)||x.box<0||x.box>4||!Number.isFinite(x.seen)||!Number.isFinite(x.wrong))throw Error('復習データを確認してください');}
 for(const h of s.history){if(!obj(h)||typeof h.id!=='string'||!Number.isFinite(h.date)||!Number.isFinite(h.score)||!Number.isFinite(h.total)||!obj(h.stats)||!Array.isArray(h.wrong))throw Error('成績データを確認してください');for(const v of Object.values(h.stats))if(!obj(v)||!Number.isFinite(v.correct)||!Number.isFinite(v.total))throw Error('分野別成績を確認してください');}
 const r=s.session;if(r&&(!obj(r)||typeof r.id!=='string'||typeof r.lesson!=='string'||!['learn','legacy','practice','review','mock'].includes(r.mode)||!Array.isArray(r.ids)||r.ids.length>200||!r.ids.every(x=>typeof x==='string')||!Number.isInteger(r.pos)||r.pos<0||r.pos>r.ids.length||!obj(r.attempts)||!obj(r.firstResults)||!obj(r.hinted)||!Array.isArray(r.rechecks)||!Array.isArray(r.wrong)||!Number.isFinite(r.elapsed)||r.elapsed<0))throw Error('途中データを確認してください');return s;
}
function load(storage){let error=null,s;const raw=storage.getItem(KEY);if(raw){try{s=validate(JSON.parse(raw));}catch(e){error=e.message;try{storage.setItem(KEY+'_unreadable',raw);}catch{}try{const backup=storage.getItem(KEY+'_backup');if(backup)s=validate(JSON.parse(backup));}catch{}}}if(!s){s=fresh();try{const old=JSON.parse(storage.getItem('yuzu_eiken5_prep_v1')||'{}');for(const [k,v]of Object.entries(old||{})){if(/^lesson\d+$/.test(k)&&v&&typeof v==='object')s.legacy[k]={cleared:!!v.cleared,best:Number(v.best)||0,perfect:!!v.perfect};}if(!storage.getItem('yuzu_g5_legacy_backup')&&Object.keys(s.legacy).length)storage.setItem('yuzu_g5_legacy_backup',JSON.stringify(old));}catch(e){error=error||'以前の記録を読み込めませんでした';}}return {state:s,error};}
function save(storage,s){validate(s);const next=JSON.stringify(s),raw=storage.getItem(KEY);if(raw===next)return;if(raw){try{validate(JSON.parse(raw));storage.setItem(KEY+'_backup',raw);}catch(e){if(e.name==='QuotaExceededError')throw e;}}storage.setItem(KEY,next);}
function record(s,q,{ok,first,hinted=false,ms=0,now=Date.now()}){const p=s.items[q.id]||(s.items[q.id]={skill:q.skill,seen:0,firstCorrect:0,wrong:0,box:0,due:now,streak:0});p.seen++;p.last=now;p.lastMs=ms;p.skill=q.skill;if(!ok){p.wrong++;p.box=0;p.streak=0;p.due=now;p.unresolved=true;}else{p.unresolved=false;if(first&&!hinted){p.firstCorrect++;if(now>=p.due){p.streak++;p.box=Math.min(4,p.box+1);p.due=now+[1,3,7,14][p.box-1]*DAY;}}else{p.streak=0;p.box=0;p.due=now+DAY;}}return p;}
function reviewIds(s,bank,{now=Date.now(),limit=3,exclude=[]}={}){const skip=new Set(exclude);return Object.entries(s.items).filter(([id,p])=>bank[id]&&p.due<=now&&!skip.has(id)).sort((a,b)=>Number(!!b[1].unresolved)-Number(!!a[1].unresolved)||a[1].due-b[1].due||b[1].wrong-a[1].wrong).slice(0,limit).map(x=>x[0]);}
function session(lesson,ids,mode='learn'){return {id:'run-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),lesson,ids:[...ids],mode,pos:0,attempts:{},firstResults:{},wrong:[],rechecks:[],hinted:{},started:Date.now(),elapsed:0,readingDone:false};}
function answer(s,q,ok,now=Date.now()){const r=s.session;if(!r||r.ids[r.pos]!==q.id)return false;const attemptKey=r.pos;const first=!r.firstResults[q.id];r.attempts[attemptKey]=(r.attempts[attemptKey]||0)+1;if(first)r.firstResults[q.id]={id:q.id,ok,skill:q.skill,hinted:!!r.hinted[attemptKey]};record(s,q,{ok,first,hinted:!!r.hinted[attemptKey],now});if(!ok&&!r.wrong.includes(q.id))r.wrong.push(q.id);if(!ok&&r.mode!=='mock'&&!r.rechecks.includes(q.id)){r.ids.splice(Math.min(r.pos+4,r.ids.length),0,q.id);r.rechecks.push(q.id);}if(ok||r.mode==='mock')r.pos++;return true;}
function finish(s,now=Date.now()){const r=s.session;if(!r)return null;if(s.history.some(h=>h.id===r.id)){s.session=null;return null;}const values=Object.values(r.firstResults),score=values.filter(x=>x.ok).length;const stats={};for(const v of values){stats[v.skill]||={correct:0,total:0};stats[v.skill].total++;if(v.ok)stats[v.skill].correct++;}const h={id:r.id,lesson:r.lesson,mode:r.mode,score,total:values.length,wrong:[...r.wrong],stats,date:now,elapsed:r.elapsed};s.history.unshift(h);s.history=s.history.slice(0,100);let coins=0;if(r.mode==='learn'||r.mode==='legacy'){const p=s.lessons[r.lesson]||{clears:0};const was=!!p.cleared;p.cleared=true;p.clears++;p.best=Math.max(p.best||0,values.length?Math.round(score/values.length*100):0);p.perfect=!!p.perfect||r.wrong.length===0;p.last=now;s.lessons[r.lesson]=p;if(!was)coins+=20;}
const date=new Date(now),day=[date.getFullYear(),date.getMonth()+1,date.getDate()].join('-');if(!s.dayRewards[day]){coins+=10;s.dayRewards[day]=true;}if(r.mode==='review'&&r.wrong.length===0&&!s.earned['review-'+day]){coins+=10;s.earned['review-'+day]=true;}if(r.wrong.length===0&&!s.earned['perfect-'+r.lesson]&&r.mode==='learn'){coins+=5;s.earned['perfect-'+r.lesson]=true;}s.coins+=coins;h.coins=coins;s.session=null;return h;}
function clearCount(s){const legacy=new Set(Object.entries(s.legacy).filter(([,v])=>v.cleared).map(([k])=>'legacy-'+k.replace('lesson','')));Object.entries(s.lessons).filter(([,v])=>v.cleared).forEach(([id])=>legacy.add(id));return legacy.size;}
function town(s){const count=clearCount(s);return {count,stage:count>=20?3:count>=10?2:count>=1?1:0,next:count<1?1:count<10?10:count<20?20:null};}
return {VERSION,KEY,DAY,shuffle,fresh,validate,load,save,record,reviewIds,session,answer,finish,clearCount,town};
});
