const G5_DATA={
  n:1,
  title:'動詞フレーズ①',
  icon:'🏃',
  phrases:[
    ['buy a book','本を買う','buy','📘'],['come here','ここに来る','come','👋'],['eat sandwiches','サンドイッチを食べる','eat','🥪'],['go to school','学校へ行く','go','🏫'],['help my mother','お母さんを助ける','help','🤝'],['live in Japan','日本に住んでいる','live','🇯🇵'],['join a soccer team','サッカーチームに参加する','join','⚽'],
    ['open a door','ドアを開ける','open','🚪'],['play soccer','サッカーをする','play','⚽'],['read a book','本を読む','read','📖'],['sing a song','歌を歌う','sing','🎤'],['talk with my friends','友達と話す','talk','💬'],['drive a car','車を運転する','drive','🚗'],['have a house','家を持っている','have','🏠']
  ]
};
const G5_KEY='yuzu_eiken5_prep_v1';
let g5Store=JSON.parse(localStorage.getItem(G5_KEY)||'{"lesson1":{"best":0,"cleared":false,"lectureSeen":false}}');
if(!g5Store.lesson1)g5Store.lesson1={best:0,cleared:false,lectureSeen:false};
const g5State={stage:0,idx:0,queue:[],wrong:new Set(),choices:[],picked:[],challenge:[],challengeScore:0};
function g5Save(){localStorage.setItem(G5_KEY,JSON.stringify(g5Store));}
function g5Shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function g5PickOther(field,correct,n=3){return g5Shuffle([...new Set(G5_DATA.phrases.map(x=>x[field]).filter(x=>x!==correct))]).slice(0,n)}
function ensureCourseUi(){
  if(document.getElementById('courseGate'))return;
  const gate=document.createElement('div');gate.id='courseGate';gate.className='courseGate';gate.innerHTML=`<div class='courseGateIn'><div class='courseGateTitle'>📘 Yuzu English</div><div class='courseGateSub'>今日はどのコースを勉強する？</div><div class='courseGrid'><button class='courseCard bronze' onclick="selectCourse('bronze')"><div class='courseEmoji'>🥉</div><h2>ブロンズ対策</h2><p>これまでのLesson。単語・リスニング・会話・文法をまとめて復習。</p><span class='courseTag'>今までのコース</span></button><button class='courseCard grade5' onclick="selectCourse('grade5')"><div class='courseEmoji'>⭐</div><h2>英検5級 準備</h2><p>単語を1語ずつではなく、使えるフレーズと基本文法で覚える。</p><span class='courseTag'>NEW · Lesson 1から</span></button></div></div>`;document.body.appendChild(gate);
  const sw=document.createElement('button');sw.className='courseSwitch';sw.textContent='⇄ コース選択';sw.onclick=showCourseGate;document.querySelector('.topActions')?.appendChild(sw);
  const g5home=document.createElement('section');g5home.id='g5Home';g5home.className='hidden';g5home.innerHTML=`<div class='g5Wrap'><div class='g5Hero'><h1>⭐ 英検5級 準備</h1><p>単語だけでなく「buy a book」「go to school」のような、英語のかたまりで覚えていこう。</p></div><div id='g5LessonList'></div></div>`;document.querySelector('.app')?.insertBefore(g5home,document.getElementById('play'));
  const g5play=document.createElement('section');g5play.id='g5Play';g5play.className='hidden playWrap';g5play.innerHTML=`<div class='navRow'><button class='back' onclick='g5BackHome()'>← 5級準備</button><div class='navTitle'>英検5級 準備</div></div><div class='panel'><div class='headline'><h2 id='g5Title'>Lesson 1</h2><div class='scorepill' id='g5Score'>0 / 0</div></div><div class='stageRow' id='g5StageRow'></div><div class='bar'><i id='g5Bar'></i></div><div id='g5Body'></div></div>`;document.querySelector('.app')?.insertBefore(g5play,document.querySelector('.confetti'));
  renderG5Home();
}
function showCourseGate(){document.getElementById('courseGate')?.classList.remove('hidden')}
function selectCourse(c){document.getElementById('courseGate')?.classList.add('hidden');document.getElementById('home')?.classList.add('hidden');document.getElementById('play')?.classList.add('hidden');document.getElementById('g5Home')?.classList.add('hidden');document.getElementById('g5Play')?.classList.add('hidden');if(c==='bronze'){document.getElementById('home')?.classList.remove('hidden');renderCards();}else{document.getElementById('g5Home')?.classList.remove('hidden');renderG5Home();}}
function renderG5Home(){const p=g5Store.lesson1;document.getElementById('g5LessonList').innerHTML=`<button class='g5LessonCard' onclick='startG5Lesson()'><div class='g5LessonTop'><div class='g5LessonIcon'>🏃</div><div style='text-align:right'><div class='count'>${p.cleared?'CLEAR':'STEP'} ${p.best||0}/8</div><div class='smallTag'>Lesson 1</div></div></div><h3>動詞フレーズ①</h3><p>buy a book / go to school / read a book など、よく使う動詞を「かたまり」で覚える。</p><div class='g5Progress'><i style='width:${Math.round((p.best||0)/8*100)}%'></i></div></button>`;}
function startG5Lesson(){document.getElementById('g5Home').classList.add('hidden');document.getElementById('g5Play').classList.remove('hidden');g5State.stage=g5Store.lesson1.lectureSeen?1:0;g5State.idx=0;g5State.queue=g5Shuffle([...Array(G5_DATA.phrases.length).keys()]);g5State.wrong=new Set();g5State.challengeScore=0;renderG5();}
function g5BackHome(){document.getElementById('g5Play').classList.add('hidden');document.getElementById('g5Home').classList.remove('hidden');renderG5Home();}
const G5_STAGES=['📘 ミニレクチャー','① 意味4択','② リスニング','③ 動詞を選ぶ','④ 間違い復習','⑤ 英文完成','⑥ 日本語→英語','⑦ 並び替え','⑧ 5級チャレンジ'];
function g5Header(total=1){document.getElementById('g5StageRow').innerHTML=G5_STAGES.slice(1).map((s,i)=>`<div class='stageChip ${g5State.stage===i+1?'on':g5State.stage>i+1?'done':''}'>${s}</div>`).join('');document.getElementById('g5Score').textContent=g5State.stage===0?'LESSON':`${Math.min(g5State.idx,total)} / ${total}`;document.getElementById('g5Bar').style.width=g5State.stage===0?'0%':`${Math.min(100,(g5State.idx/Math.max(total,1))*100)}%`;}
function g5SetBest(n){g5Store.lesson1.best=Math.max(g5Store.lesson1.best||0,n);g5Save();}
function renderG5(){if(g5State.stage===0)return renderG5Lecture();if(g5State.stage===1)return renderG5Meaning();if(g5State.stage===2)return renderG5Listening();if(g5State.stage===3)return renderG5Verb();if(g5State.stage===4)return renderG5Review();if(g5State.stage===5)return renderG5Complete();if(g5State.stage===6)return renderG5JpToEn();if(g5State.stage===7)return renderG5Order();if(g5State.stage===8)return renderG5Challenge();return finishG5();}
function renderG5Lecture(){g5Header();document.getElementById('g5Body').innerHTML=`<div class='g5Lecture'><div class='g5ChallengeLabel'>Lesson 1 のポイント</div><h3>動詞は「かたまり」で覚えよう</h3><div class='g5LecturePoint'><b class='g5Verb'>buy</b> = 買う → <b>buy a book</b> = 本を買う<br><b class='g5Verb'>go</b> = 行く → <b>go to school</b> = 学校へ行く<br><b class='g5Verb'>read</b> = 読む → <b>read a book</b> = 本を読む</div><div class='g5LecturePoint'>英検5級では、動詞1語だけよりも <b>動詞 + もの / 場所</b> のセットで覚えると問題が解きやすいよ。</div><div class='actionRow'><button class='ghost' onclick="speak('buy a book. go to school. read a book.')">🔊 例文を聞く</button><button class='main' onclick='g5StartAfterLecture()'>練習スタート</button></div></div>`;}
function g5StartAfterLecture(){g5Store.lesson1.lectureSeen=true;g5Save();g5State.stage=1;g5State.idx=0;renderG5();}
function renderG5Meaning(){g5SetBest(1);if(g5State.idx>=g5State.queue.length){g5State.stage=2;g5State.idx=0;return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5State.choices=g5Shuffle([p[1],...g5PickOther(1,p[1])]);g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>① 意味4択</div><div class='g5Phrase'>${p[0]}</div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice jp' onclick='g5AnswerMeaning(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;}
function g5AnswerMeaning(i){const idx=g5State.queue[g5State.idx],p=G5_DATA.phrases[idx];g5Feedback(i,p[1],()=>g5State.wrong.add(idx));}
function renderG5Listening(){g5SetBest(2);if(g5State.idx>=g5State.queue.length){g5State.stage=3;g5State.idx=0;return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5State.choices=g5Shuffle([p[1],...g5PickOther(1,p[1])]);g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>② リスニング4択</div><div class='center'><button class='speakerBtn' onclick="speak(${JSON.stringify(p[0])})"><img src='speaker.svg'><span>英語を聞く</span></button></div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice jp' onclick='g5AnswerListen(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;setTimeout(()=>speak(p[0]),250);}
function g5AnswerListen(i){const idx=g5State.queue[g5State.idx],p=G5_DATA.phrases[idx];g5Feedback(i,p[1],()=>g5State.wrong.add(idx));}
function renderG5Verb(){g5SetBest(3);if(g5State.idx>=g5State.queue.length){g5State.stage=4;g5State.idx=0;g5State.queue=g5Shuffle([...g5State.wrong]);return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]],rest=p[0].replace(new RegExp('^'+p[2]+'\\s*'),'');g5State.choices=g5Shuffle([p[2],...g5PickOther(2,p[2])]);g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>③ 動詞を選ぼう</div><div class='g5Phrase'>_____ ${rest}</div><div class='g5Meaning'>${p[1]}</div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice' onclick='g5AnswerVerb(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;}
function g5AnswerVerb(i){const idx=g5State.queue[g5State.idx],p=G5_DATA.phrases[idx];g5Feedback(i,p[2],()=>g5State.wrong.add(idx));}
function renderG5Review(){g5SetBest(4);if(!g5State.queue.length||g5State.idx>=g5State.queue.length){g5State.stage=5;g5State.idx=0;g5State.queue=g5Shuffle([...Array(G5_DATA.phrases.length).keys()]);return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5State.choices=g5Shuffle([p[0],...g5PickOther(0,p[0])]);g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>④ 間違い復習</div><div class='bigEmoji center'>${p[3]}</div><div class='g5Meaning'>${p[1]}</div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice' onclick='g5AnswerReview(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;}
function g5AnswerReview(i){const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5Feedback(i,p[0]);}
function renderG5Complete(){g5SetBest(5);if(g5State.idx>=g5State.queue.length){g5State.stage=6;g5State.idx=0;return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]],rest=p[0].replace(new RegExp('^'+p[2]+'\\s*'),'');g5State.choices=g5Shuffle([p[2],...g5PickOther(2,p[2])]);g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>⑤ 英文完成</div><div class='g5Phrase'>I _____ ${rest}.</div><div class='g5Meaning'>「私は${p[1]}」</div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice' onclick='g5AnswerComplete(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;}
function g5AnswerComplete(i){const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5Feedback(i,p[2]);}
function renderG5JpToEn(){g5SetBest(6);if(g5State.idx>=g5State.queue.length){g5State.stage=7;g5State.idx=0;return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5State.choices=g5Shuffle([p[0],...g5PickOther(0,p[0])]);g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>⑥ 日本語 → 英語</div><div class='g5Phrase'>${p[1]}</div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice' onclick='g5AnswerJp(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;}
function g5AnswerJp(i){const p=G5_DATA.phrases[g5State.queue[g5State.idx]];g5Feedback(i,p[0]);}
function renderG5Order(){g5SetBest(7);if(g5State.idx>=g5State.queue.length){g5State.stage=8;g5State.idx=0;g5State.challenge=g5Shuffle([...Array(G5_DATA.phrases.length).keys()]).slice(0,5);return renderG5()}const p=G5_DATA.phrases[g5State.queue[g5State.idx]],full='I '+p[0]+'.',tokens=g5Shuffle(full.replace('.','').split(' '));g5State.choices=tokens;g5State.picked=[];g5Header(g5State.queue.length);document.getElementById('g5Body').innerHTML=`<div class='sub'>⑦ 並び替え</div><div class='g5Meaning'>私は${p[1]}</div><div class='answerBox' id='g5AnswerBox'></div><div class='tokens'>${tokens.map((t,i)=>`<button class='token' id='g5tok${i}' onclick='g5PickToken(${i})'>${t}</button>`).join('')}</div><div class='actionRow'><button class='ghost' onclick='g5Undo()'>1つ戻す</button><button class='main' onclick="g5CheckOrder(${JSON.stringify(full.replace('.',''))})">答える</button></div><div class='feedback' id='g5Fb'></div>`;}
function g5PickToken(i){if(g5State.picked.includes(i))return;g5State.picked.push(i);document.getElementById('g5tok'+i).classList.add('used');document.getElementById('g5AnswerBox').textContent=g5State.picked.map(x=>g5State.choices[x]).join(' ');}
function g5Undo(){const i=g5State.picked.pop();if(i===undefined)return;document.getElementById('g5tok'+i).classList.remove('used');document.getElementById('g5AnswerBox').textContent=g5State.picked.map(x=>g5State.choices[x]).join(' ');}
function g5CheckOrder(correct){const ans=g5State.picked.map(x=>g5State.choices[x]).join(' ');document.getElementById('g5Fb').textContent=ans===correct?'正解！':`正解は ${correct}.`;ans===correct?playGood():playBad();g5State.idx++;setTimeout(renderG5,850);}
function renderG5Challenge(){g5SetBest(8);if(g5State.idx>=5)return finishG5();const p=G5_DATA.phrases[g5State.challenge[g5State.idx]];g5State.choices=g5Shuffle([p[0],...g5PickOther(0,p[0])]);g5Header(5);document.getElementById('g5Body').innerHTML=`<div class='g5ChallengeLabel'>⑧ 5級チャレンジ ${g5State.idx+1}/5</div><div class='g5Phrase'>${p[1]}</div><div class='choiceGrid'>${g5State.choices.map((c,i)=>`<button class='choice' onclick='g5AnswerChallenge(${i})'>${c}</button>`).join('')}</div><div class='feedback' id='g5Fb'></div>`;}
function g5AnswerChallenge(i){const p=G5_DATA.phrases[g5State.challenge[g5State.idx]];if(g5State.choices[i]===p[0])g5State.challengeScore++;g5Feedback(i,p[0]);}
function finishG5(){g5Store.lesson1.cleared=true;g5Store.lesson1.best=8;g5Save();g5Header(5);document.getElementById('g5Bar').style.width='100%';document.getElementById('g5Body').innerHTML=`<div class='finish'><div class='bigEmoji'>⭐</div><h3>Lesson 1 CLEAR!</h3><p class='note'>動詞は「1語」より「フレーズ」で覚えると、5級の問題で使いやすいよ。</p><div class='heroBadge'>🏃 Verb Phrase Starter</div><div class='actionRow' style='margin-top:16px'><button class='ghost' onclick='g5Store.lesson1.lectureSeen=false;g5Save();startG5Lesson()'>📘 レクチャーから復習</button><button class='main' onclick='g5BackHome()'>5級準備へ</button></div></div>`;playClear();}
function g5Feedback(i,correct,onWrong){[...document.querySelectorAll('#g5Body .choice')].forEach(b=>b.disabled=true);const ans=g5State.choices[i],btns=[...document.querySelectorAll('#g5Body .choice')];if(ans===correct){btns[i].classList.add('good');document.getElementById('g5Fb').textContent='正解！';playGood();}else{btns[i].classList.add('bad');btns.find(b=>b.textContent===correct)?.classList.add('good');document.getElementById('g5Fb').textContent=`正解は ${correct}`;if(onWrong)onWrong();playBad();}g5State.idx++;setTimeout(renderG5,750);}
ensureCourseUi();showCourseGate();
